# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.8.1
maven_group = alexyzer.hexcc
archives_name = hexcc
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.116.17+1.21.1
neoforge_version = 21.1.248

cc_tweaked_version = 1.120.2
hexcasting_version = 0.12.0-devel-pre-34

# Runtime only
architecturyVersion=13.0.2
kotlinForForgeVersion = 5.8.0
fabricLanguageKotlinVersion = 1.13.7+kotlin.2.2.21

paucal_version = 0.7.1-pre-27
patchouli_version = 88
inline_version = 1.2.2-74
neoforge_caelus_version = 7.0.1
cloth_config_version = 15.0.140
fabric_cardinal_components_version = 6.1.3