modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "hexcc"
version = "${version}"
displayName = "HexCC"
authors = "alexyzer"
description = '''
Hex Casting - CC:Tweaked interop.
'''
#logoFile = ""

[[dependencies.hexcc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcc]]
modId = "hexcasting"
type = "required"
versionRange = "[0.12.0-devel-pre-26,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcc]]
modId = "computercraft"
type = "required"
versionRange = "[1.113.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "hexcc.mixins.json"
